export const purchaseState = {
  ERROR: '0',
  PURCHASED: '1',
  SHIPPED: '2',
  COMPLETED: '3',
  BUYER_CANCELLED: '4',
  SELLER_CANCELLED: '5',
  SELLER_SHIPPING_TIMEOUT: '6',
  BUYER_CONFIRMATION_TIMEOUT: '7',
  NEW: '-1',
  PENDING_PURCHASED: '-2',
  PENDING_SHIPPED: '-3',
  PENDING_COMPLETED: '-4',
  PENDING_CANCELLED: '-5'
}
